DATAPREPROCESSING:
  Foldering:
    case_name: case_sample
    my_dir: ../dataset/
    train_dir: cycle1,cycle2,cycle3,cycle4
    val_dir: cycle5
  
  Foldering_Random:
    case_name: case_sample
    my_dir: ../dataset/case_data/
    threshold: 1000
  
  Video_to_frame:
    input_dir: ../dataset/test_data/cycle2.mp4
    output_dir: ../dataset/test_data/
  
  Frame_to_video:
    input_dir: ../dataset/test_data/resized_XX/
    output_dir: ../dataset/test_data/XX.mp4
  
  FormatRevision:
    label_list: os.listdir("**dir")
    image_list: os.listdir("**dir")
    
  Augmentation:
    input_dir : /home/obayashi/data/Used_worker_data/220318_Used/Adjust_New_Worker/train/
    output_dir : /home/obayashi/data/Used_worker_data/220407_augmentation/
    size : 4



OBJECT_DETECTION:
  training:
    #Set Input file & Output file directory path
    traindata : './dataset/case_data/case_sample/case_sample.yaml'
    pre_weights : './weights/OD_train_result/result_1121_epoch100_30/weights/best.pt'
    save_name : 'case_sample'
    save_dir : './weights/OD_train_result/'
    
    #set training condition
    batch : '4'
    epochs : '10'

  prediction:
    #Set Input file & Output file directory path
    file_name: 'cycle2.mp4'
    detect_model: '../codes/yolov5/detect_Draw_Line.py'
    source: '../dataset/test_data/'
    weights: '../weights/OD_train_result/result_1121_epoch100_30/weights/best.pt'
    save_dir: '../results/OD_predict_result/'
    
    #set prediction condition
    conf: '0.25'
    
  postprocessing:
    #Set Input file & Output file directory path
    file_name: 'cycle2'
    path: '../results/OD_predict_result/cycle2/'
    save_dir: '../results/OD_predict_result/cycle2/'


ACTIVITY_RECOGNITION:
  train : 
    input_dir : ../dataset/activity_recognition/sample.csv
    N_TIME_STEPS : 10
    step : 1
    num_equipment : 11
    n_classes : 7
    res_dir : ../weights/AR_train_result
    epoch : 100
    
    #sensitivy analysis
    n_hidden : 64
    batch_size : 32
    
  predict : 
    input_file: ../results/OD_predict_result/cycle2/cycle2_xy_mod.csv
    trained_model : ../weights/AR_train_result/sample_lstm_epoch1_timestep10.h5
    N_TIME_STEPS : 10
    step : 1
    num_equipment : 11
    n_classes : 7
    res_dir : ../results/AR_prediction_result
    
  comparison : 
    input_file : ../dataset/activity_recognition/test.csv
    trained_model : ../weights/AR_train_result/sample_lstm_epoch1_timestep10.h5
    N_TIME_STEPS : 10
    step : 1
    num_equipment : 11
    n_classes : 7
    res_dir : ../results/AR_prediction_result/comparison
    

RESULT_ANALYSIS:
  time_table:
    input_ID_data: '../results/AR_prediction_result/cycle2_ID.csv'
    time_table_output_dir: '../results/result_analysis_result/time_table'
    time_interval: 60 #sec  
      
  activity_cycle_time:
    input_ID_data: '../results/AR_prediction_result/cycle2_ID.csv'
    cycle_time_output_dir: '../results/result_analysis_result/activity_cycle_time_result'
    activity_class: ["Drilling&Loading", "Mucking", "Scaling", "Spraying", "H_beam", "Rock_bolting", "nothing"]

  counting_dumptruck:
    input_ID_data: '../results/AR_prediction_result/cycle2_ID.csv'
    cycle_time_data: './result_analysis_result/activity_cycle_time_result/act_time.csv'
    counting_output_dir: '../results/result_analysis_result/counting_equipment'
    
  counting_payloader:
    input_XY_data: '../results/AR_prediction_result/cycle2_xy_mod.csv'
    dumptruck_counting_data: '../results/result_analysis_result/counting_equipment/dumptruck_counting.csv'
    counting_output_dir: '../results/result_analysis_result/counting_equipment'
    
  result_analysis:
    input_ID_data: '../results/AR_prediction_result/cycle2_ID_1.csv'
    input_XY_data: '../results/AR_prediction_result/cycle2_xy_mod_1.csv'
    time_table_output_dir: '../results/result_analysis_result/time_table'
    cycle_time_output_dir: '../results/result_analysis_result/activity_cycle_time_result'
    cycle_time_data: '../results/result_analysis_result/activity_cycle_time_result/act_time.csv'
    counting_output_dir: '../results/result_analysis_result/counting_equipment'
    dumptruck_counting_data: '../results/result_analysis_result/counting_equipment/dumptruck_counting.csv'
    time_interval: 60 #sec  
    activity_class: ["Drilling&Loading", "Mucking", "Scaling", "Spraying", "H_beam", "Rock_bolting", "nothing"]



